services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: audionexus-manager
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./app:/app
      - ./data/audionexus:/data/audionexus
      - ./data/config:/app/config
      - ./data/database:/data/database
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - audionexus-network

  db:
    image: postgres:15-alpine
    container_name: audionexus-db
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./data/database:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - audionexus-network

  redis:
    image: redis:7-alpine
    container_name: audionexus-redis
    restart: unless-stopped
    networks:
      - audionexus-network

  nginx:
    image: nginx:alpine
    container_name: audionexus-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - app
    networks:
      - audionexus-network

  certbot:
    image: certbot/certbot
    container_name: audionexus-certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email -d ${DOMAIN_NAME} --dry-run

networks:
  audionexus-network:
    driver: bridge

volumes:
  postgres_data:
