"""Initial migration

Revision ID: 85bc7f0e10f4
Revises: 
Create Date: 2025-07-05 14:07:50.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '85bc7f0e10f4'
down_revision = None
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Créer d'abord les tables sans dépendances
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    
    # 2. Créer les utilisateurs (dépend de rien)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # 3. Créer les bibliothèques (dépend de users)
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.create_index(op.f('ix_libraries_id'), 'libraries', ['id'], unique=False)
    
    # 4. Créer les livres audio (dépend de libraries et users)
    op.create_table('audiobooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('authors', mysql.JSON(), nullable=True),
    sa.Column('narrators', mysql.JSON(), nullable=True),
    sa.Column('series', mysql.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('publish_year', sa.Integer(), nullable=True),
    sa.Column('genres', mysql.JSON(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('cover_path', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('abridged', sa.Boolean(), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # 5. Créer la table de liaison user_roles (dépend de users et roles)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    
    # 6. Créer la table books (dépend de libraries et users)
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('authors', mysql.JSON(), nullable=True),
    sa.Column('narrators', mysql.JSON(), nullable=True),
    sa.Column('series', mysql.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('publish_year', sa.Integer(), nullable=True),
    sa.Column('genres', mysql.JSON(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('cover_path', sa.String(length=255), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('explicit', sa.Boolean(), nullable=True),
    sa.Column('abridged', sa.Boolean(), nullable=True),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # 7. Créer la table de liaison book_tags (dépend de books et tags)
    op.create_table('book_tags',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'tag_id')
    )
    
    # 8. Créer les chapitres (dépend de books)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapters_id'), 'chapters', ['id'], unique=False)
    
    # 9. Créer la progression des livres audio (dépend de users et audiobooks)
    op.create_table('audiobook_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('audiobook_id', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('current_time', sa.Float(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_played', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['audiobook_id'], ['audiobooks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'audiobook_id', name='_user_audiobook_uc')
    )
    
    # 10. Créer les index pour les tables
    op.create_index(op.f('ix_audiobooks_id'), 'audiobooks', ['id'], unique=False)
    op.create_index(op.f('ix_audiobooks_external_id'), 'audiobooks', ['external_id'], unique=False)
    op.create_index(op.f('ix_audiobooks_isbn'), 'audiobooks', ['isbn'], unique=False)
    op.create_index(op.f('ix_audiobooks_library_id'), 'audiobooks', ['library_id'], unique=False)
    op.create_index('ix_audiobooks_library_title', 'audiobooks', ['library_id', 'title'], unique=False)
    
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    
    op.create_index(op.f('ix_audiobook_progress_audiobook_id'), 'audiobook_progress', ['audiobook_id'], unique=False)
    op.create_index(op.f('ix_audiobook_progress_id'), 'audiobook_progress', ['id'], unique=False)
    op.create_index(op.f('ix_audiobook_progress_user_id'), 'audiobook_progress', ['user_id'], unique=False)
    
    # Les index sur les colonnes JSON sont créés séparément après la création des tables
    # car ils nécessitent une configuration spéciale pour MySQL
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # L'ordre de suppression est l'inverse de la création pour respecter les contraintes de clés étrangères
    
    # 1. Supprimer d'abord les index
    op.drop_index(op.f('ix_chapters_id'), table_name='chapters')
    
    op.drop_index(op.f('ix_audiobook_progress_user_id'), table_name='audiobook_progress')
    op.drop_index(op.f('ix_audiobook_progress_id'), table_name='audiobook_progress')
    op.drop_index(op.f('ix_audiobook_progress_audiobook_id'), table_name='audiobook_progress')
    
    op.drop_index('ix_audiobooks_library_title', table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_library_id'), table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_isbn'), table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_id'), table_name='audiobooks')
    op.drop_index(op.f('ix_audiobooks_external_id'), table_name='audiobooks')
    
    # 2. Supprimer les tables avec des clés étrangères en premier
    op.drop_table('chapters')
    op.drop_table('book_tags')
    op.drop_table('audiobook_progress')
    op.drop_table('books')
    op.drop_table('audiobooks')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_libraries_id'), table_name='libraries')
    op.drop_table('libraries')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
